// <auto-generated />
using System;
using CodeWithQB.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeWithQB.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180902075521_Snapshots")]
    partial class Snapshots
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeWithQB.Core.Models.Snapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AsOfDateTime");

                    b.Property<string>("Data");

                    b.HasKey("SnapshotId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("CodeWithQB.Core.Models.StoredEvent", b =>
                {
                    b.Property<Guid>("StoredEventId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aggregate");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Data");

                    b.Property<string>("DotNetType");

                    b.Property<int>("Sequence");

                    b.Property<Guid>("StreamId");

                    b.Property<string>("Type");

                    b.Property<int>("Version");

                    b.HasKey("StoredEventId");

                    b.ToTable("StoredEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
